name: Upload Static Files (Diff)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  upload:
    name: Upload Static Files to COS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'

      - name: Build Hugo
        run: hugo --minify

      - name: Calculate SHA256
        run: find public -type f -exec sha256sum {} \; > public/sha256sum.txt
      
      - name: Download Previous SHA256
        run: curl -fsSl https://tajuren.cn/sha256sum.txt -o sha256sum.txt || touch sha256sum.txt

      - name: Calculate Diff and Minimize Upload Size
        run: "[ -f sha256sum.txt ] && ./incremental-diff.sh"
          

      - name: Upload Static Files to COS
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: public
          remote_path: .
          clean: false
