name: Upload Static Files (Full)

on:
  schedule:
    # CST 4AM
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  upload:
    name: Upload Static Files to COS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'

      - name: Build Hugo
        run: hugo --minify

      - name: Calculate SHA256
        run: find public -type f -exec sha256sum {} \; > public/sha256sum.txt

      - name: Upload Static Files to COS
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: public
          remote_path: .
          clean: true
